### ISSUE TITLE
Erro ao adicionar meu histórico

### ISSUE THREAD

**Issue by nickolasrm** [juliarobaina/Meu-Coeficiente-De-Rendimento#1]
Baixei meu histórico e minha matrícula para calcular o CR, mas foi retornado um erro. Segue as imagens do programa:

- [Fç até determinado periodo](https://ibb.co/kDxN7gL)

- [Fç calcular cr](https://ibb.co/tDGQLFJ)

Se precisar do meu histórico, me chama no pvd que envio!

**Comment by juliarobaina** [comment]
O readme do repositório foi atualizado com informações de uso do programa no Windows, peço que leia e veja se seu problema foi corrigido.

**Comment by nickolasrm** [comment]
Testei aqui e funcionou! Era a questão de instalar o ghostscript mesmo.
Também adicionei um requirements.txt para facilitar a instalação das libs.

Depois dê uma olhada o pr que fiz para ver se está de acordo #3
